before:
  hooks:
  - go mod tidy
  - go generate ./...

builds:
- main: ./cmd/kubectl-colorize_managed_fields
  binary: kubectl-colorize_managed_fields
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64

archives:
- format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
